'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "products",
      [
        {
          id: 1,
          name: "Alpukat Madu",
          price: 52000,
          image: "public/p1.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 2,
          name: "Anggur Merah Seedless",
          price: 76000,
          image: "public/p2.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 3,
          name: "Apel Super Fuji",
          price: 40000,
          image: "public/p3.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 4,
          name: "Blueberry Lokal",
          price: 25000,
          image: "public/p4.jpg",
          description: "Harga Per-100 Gram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 5,
          name: "Buah Naga Merah",
          price: 42000,
          image: "public/p5.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 6,
          name: "Jambu Biji",
          price: 20000,
          image: "public/p6.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 7,
          name: "Jeruk Mandarin",
          price: 60000,
          image: "public/p7.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 8,
          name: "Kiwi Premium",
          price: 25000,
          image: "public/p8.jpg",
          description: "Harga Per-100 gram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 9,
          name: "Lemon Import",
          price: 32000,
          image: "public/p9.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 10,
          name: "Markisa Lokal",
          price: 39000,
          image: "public/p10.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 11,
          name: "Melon Reguler",
          price: 35000,
          image: "public/p11.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 12,
          name: "Nanas Madu",
          price: 19000,
          image: "public/p12.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 1,
        },
        {
          id: 13,
          name: "Pakcoy",
          price: 5000,
          image: "public/p13.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 2,
        },
        {
          id: 14,
          name: "Daun Basil",
          price: 10000,
          image: "public/p14.jpg",
          description: "Harga Per-100 gram",
          isDeleted: 0,
          product_categories_id: 2,
        },
        {
          id: 15,
          name: "Brokoli",
          price: 20000,
          image: "public/p15.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 2,
        },
        {
          id: 16,
          name: "Cabai Merah Keriting",
          price: 10000,
          image: "public/p16.jpg",
          description: "Harga Per-100 gram",
          isDeleted: 0,
          product_categories_id: 2,
        },
        {
          id: 17,
          name: "Daun Bawang",
          price: 4000,
          image: "public/p17.jpg",
          description: "Harga Per-100 gram",
          isDeleted: 0,
          product_categories_id: 2,
        },
        {
          id: 18,
          name: "Daging Sapi Lokal Potong Kecil",
          price: 40000,
          image: "public/p18.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 3,
        },
        {
          id: 19,
          name: "Daging Sapi Lokal Giling",
          price: 40000,
          image: "public/p19.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 3,
        },
        {
          id: 20,
          name: "Daging Sapi Lokal Potong Dadu",
          price: 40000,
          image: "public/p20.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 3,
        },
        {
          id: 21,
          name: "Minyak Goreng Fortune",
          price: 18000,
          image: "public/p21.jpg",
          description: "Harga Per-Liter",
          isDeleted: 0,
          product_categories_id: 4,
        },
        {
          id: 22,
          name: "Garam Dolphin",
          price: 4000,
          image: "public/p22.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 4,
        },
        {
          id: 23,
          name: "Gula Rose Brand Premium",
          price: 15000,
          image: "public/p23.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 4,
        },
        {
          id: 24,
          name: "Tepung Segitiga Biru",
          price: 15000,
          image: "public/p24.jpg",
          description: "Harga Per-Kilogram",
          isDeleted: 0,
          product_categories_id: 4,
        },
        {
          id: 25,
          name: "Cumi-Cumi",
          price: 30000,
          image: "public/p25.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 5,
        },
        {
          id: 26,
          name: "Cumi-Cumi Ring Kupas",
          price: 35000,
          image: "public/p26.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 5,
        },
        {
          id: 27,
          name: "Ikan Gurame Utuh",
          price: 40000,
          image: "public/p27.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 5,
        },
        {
          id: 28,
          name: "Ikan Dori Fillet",
          price: 30000,
          image: "public/p28.jpg",
          description: "Harga Per-300 gram",
          isDeleted: 0,
          product_categories_id: 5,
        },
        {
          id: 29,
          name: "Ikan Salmon Potong",
          price: 80000,
          image: "public/p29.jpg",
          description: "Harga Per-300 gram",
          isDeleted: 0,
          product_categories_id: 5,
        },
        {
          id: 30,
          name: "Tiram Utuh",
          price: 25000,
          image: "public/p30.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 5,
        },
        {
          id: 31,
          name: "Ketumbar Bubuk",
          price: 1000,
          image: "public/p31.jpg",
          description: "Harga Per-15 gram",
          isDeleted: 0,
          product_categories_id: 6,
        },
        {
          id: 32,
          name: "Bumbu Balado",
          price: 5000,
          image: "public/p32.jpg",
          description: "Harga Per-50 gram",
          isDeleted: 0,
          product_categories_id: 6,
        },
        {
          id: 33,
          name: "Bumbu Kaldu Jamur",
          price: 25000,
          image: "public/p33.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 6,
        },
        {
          id: 34,
          name: "Bumbu Kaldu Ayam",
          price: 10000,
          image: "public/p34.jpg",
          description: "Harga Per-200 gram",
          isDeleted: 0,
          product_categories_id: 6,
        },
        {
          id: 35,
          name: "Ayam Broiler Premium",
          price: 50000,
          image: "public/p35.jpg",
          description: "Harga Per-kilogram",
          isDeleted: 0,
          product_categories_id: 7,
        },
        {
          id: 36,
          name: "Ayam Giling",
          price: 20000,
          image: "public/p36.jpg",
          description: "Harga Per-250 gram",
          isDeleted: 0,
          product_categories_id: 7,
        },
        {
          id: 37,
          name: "Ayam Kampung Utuh",
          price: 65000,
          image: "public/p37.jpg",
          description: "Harga Per-kilogram",
          isDeleted: 0,
          product_categories_id: 7,
        },
        {
          id: 38,
          name: "Ceker Ayam",
          price: 15000,
          image: "public/p38.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 7,
        },
        {
          id: 39,
          name: "Fillet Ayam Fresh",
          price: 35000,
          image: "public/p39.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 7,
        },
        {
          id: 40,
          name: "Bakso Sapi",
          price: 50000,
          image: "public/p40.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 8,
        },
        {
          id: 41,
          name: "Indomie Kuah",
          price: 2500,
          image: "public/p41.jpg",
          description: "Harga Per-Bungkus",
          isDeleted: 0,
          product_categories_id: 8,
        },
        {
          id: 42,
          name: "Spicy Chicken Wings",
          price: 50000,
          image: "public/p42.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 8,
        },
        {
          id: 43,
          name: "Otak-Otak Ikan",
          price: 25000,
          image: "public/p43.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 8,
        },
        {
          id: 44,
          name: "Tahu Putih",
          price: 15000,
          image: "public/p44.jpg",
          description: "Harga Per-500 gram",
          isDeleted: 0,
          product_categories_id: 9,
        },
        {
          id: 45,
          name: "Telur Asin",
          price: 20000,
          image: "public/p45.jpg",
          description: "Harga Per-300 gram",
          isDeleted: 0,
          product_categories_id: 9,
        },
        {
          id: 46,
          name: "Telur Ayam",
          price: 30000,
          image: "public/p46.jpg",
          description: "Harga Per-kilogram",
          isDeleted: 0,
          product_categories_id: 9,
        },
        {
          id: 47,
          name: "Tempe Negeri",
          price: 10000,
          image: "public/p47.jpg",
          description: "Harga Per-300 gram",
          isDeleted: 0,
          product_categories_id: 9,
        },
        {
          id: 48,
          name: "Greenfields Susu UHT Chocomalt",
          price: 8000,
          image: "public/p48.jpg",
          description: "Harga Per-200ml",
          isDeleted: 0,
          product_categories_id: 10,
        },
        {
          id: 49,
          name: "Greenfields Susu UHT Strawberry",
          price: 8000,
          image: "public/p49.png",
          description: "Harga Per-200ml",
          isDeleted: 0,
          product_categories_id: 10,
        },
        {
          id: 50,
          name: "Greenfields Susu UHT Vanilla",
          price: 8000,
          image: "public/p50.jpg",
          description: "Harga Per-200ml",
          isDeleted: 0,
          product_categories_id: 10,
        },
        {
          id: 51,
          name: "Greenfields Susu UHT Low Fat",
          price: 25000,
          image: "public/p51.jpg",
          description: "Harga Per-Liter",
          isDeleted: 0,
          product_categories_id: 10,
        },
        {
          id: 52,
          name: "Greenfields Susu UHT Skimmed",
          price: 25000,
          image: "public/p52.jpg",
          description: "Harga Per-Liter",
          isDeleted: 0,
          product_categories_id: 10,
        },
        {
          id: 53,
          name: "Ultramilk Full Cream",
          price: 18000,
          image: "public/p53.jpg",
          description: "Harga Per-Liter",
          isDeleted: 0,
          product_categories_id: 10,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('products', null, {});
  }
};
